name: pfm-standalone
services:
    postgresql:
        image: postgres:17.6-alpine3.22
        container_name: pfm-standalone-postgresql
        environment:
            - POSTGRES_DB=${DB_NAME}
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
        ports:
            - "${DB_PORT}:5432"
        volumes:
            - postgresql_data:/var/lib/postgresql/data
        healthcheck:
            test:
                ["CMD-SHELL", "sh -c 'pg_isready -U ${DB_USER} -d ${DB_NAME}'"]
            interval: 10s
            timeout: 5s
            retries: 5
            start_period: 10s
    migrations_job:
        depends_on:
            postgresql:
                condition: service_healthy
        container_name: pfm-standalone-migrations_job
        pull_policy: build
        image: pfm/standalone:latest
        build:
            context: .
            dockerfile: Dockerfile.standalone
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ConnectionStrings__pfm=Host=pfm-standalone-postgresql;Port=5432;Database=${DB_NAME};Username=${DB_USER};Password=${DB_PASSWORD}
        command: ["dotnet", "/webapi/PoultryFarmManager.WebAPI.dll", "migrate"]
    app:
        depends_on:
            postgresql:
                condition: service_healthy
            migrations_job:
                condition: service_completed_successfully # Waits until container is finished
        pull_policy: never # Built once as both services (migrations_job) use the same image
        image: pfm/standalone:latest
        container_name: pfm-standalone-app
        ports:
            - "80:80"
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ConnectionStrings__pfm=Host=pfm-standalone-postgresql;Port=5432;Database=${DB_NAME};Username=${DB_USER};Password=${DB_PASSWORD}
volumes:
    postgresql_data:
        driver: local
